site_name: Yz-im
site_author: terry
repo_url: https://github.com/yz-im
nav:
  - Home: index.md
  - Documentation: 
    - server: documentation/server.md
    - web: documentation/web.md
  - Demo:
    - web: demo/web.md
    - mac: demo/mac.md
  - About: about.md