site_name: Yz-im
site_author: terry
repo_url: https://github.com/yz-im
nav:
  - Home: index.md
  - Documentation: 
    - server: documentation/server.md
    - web: documentation/web.md
  - Demo:
    - web: demo/web.md
    - mac: demo/mac.md
  - Polar: polar/intro.md
  - Cli:
    - intro: cli/intro.md
    - reference: cli/reference.md
  - Log:
    - intro: log/intro.md
  - Toolkit:
    - default: toolkit/default.md
  - About: about.md